services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: nginx_server
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: postgres:16
        container_name: postgres_db
        restart: unless-stopped
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: transcribe
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    adminer:
        image: adminer
        container_name: adminer
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            - ADMINER_DEFAULT_SERVER=db

volumes:
    pgdata:
